theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: none
  summary:
    position: content
  logo:
    footer: "/assets/images/UN_logo_stacked_French.svg"
  debug:
     productionUrl: "https://dico.unric.org"